config.json, spec/ciConf.js, spec/smokeConf.js
Chromedriver to 2.13.
CI browser version bumps for Chrome 39 and Firefox 34.
=> feat(webdriver): version bumps for chromedriver and supported browsers

CHANGELOG.md, config.json, lib/locators.js, package.json, plugins/ngHint/spec/failureConfig.js, plugins/ngHint/spec/successConfig.js, spec/basic/locators_spec.js, testapp/alt_root_index.html, testapp/app.js, testapp/index.html, testapp/shadow/shadow.html, testapp/shadow/shadow.js
Bundled a couple of small commits together to do a 1.7.0 release.
@hankduan could you take a look?
=> A collection of upgrades for 1.7 release

lib/clientsidescripts.js
=> fix(bug): by.buttonText() should not be effected by CSS style

lib/element.js, lib/protractor.js, package.json, spec/basic/elements_spec.js, spec/basic/locators_spec.js, spec/withLoginConf.js
=> fix(element): update to selenium-webdriver@2.45.1 and remove element.then

website/docgen/inline_tags/code.js
Do not try to replace special character quotes in JSON.
Closes #2163
=> chore(website): fix API section of website

docs/webdriver-vs-protractor.md
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular/protractor/2289)
=> chore(website): more protractor vs vanilla wd documentation

config.json, spec/ciFullConf.js, spec/ciSmokeConf.js
Updating Selenium standalone from 2.45.0 to 2.47.0
Updating ChromeDriver from 2.15 to 2.19
Selenium Changelog: https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/CHANGES.md
ChromeDriver Changelog: http://chromedriver.storage.googleapis.com/2.19/notes.txt
=> feat(webdriver): update webdriver and chromedriver to latest version

website/gulpfile.js
=> chore(website): fix links to github files

website/docgen/dgeni-config.js, website/docgen/processors/filter-promise.js, website/package.json
=> chore(docs): include `webdriver.Key` and `webdriver.promise` in API page

lib/plugins.js
=> chore(plugins): Better error message for invalid plugin paths

docs/webdriver-vs-protractor.md
=> chore(docs): fix link in webdriver v protractor

lib/configParser.js, package.json
Not sure depending on lodash is worth it.  Let me know what you think
=> cleanup(lodash): remove lodash dependency

docs/referenceConf.js, lib/frameworks/README.md, lib/frameworks/jasmine.js, lib/frameworks/mocha.js
=> feat(config): allow onComplete to return a promise

docs/page-objects.md
Spelling mistake - `Additionaly` > `Additionally`
=> chore(docs): fix typos in page-objects.md

docs/referenceConf.js
Is there a challenge for the most basic PR ever ?
=> Fix typo in referenceConf.js

gulpfile.js, lib/protractor.js, lib/selenium-webdriver/locators.js, lib/selenium-webdriver/webdriver.js, website/docgen/dgeni-config.js
Placeholders for api documentation.
=> chore(docs): add selenium webdriver documents

lib/element.js, spec/basic/elements_spec.js
Easier to use version of webdriver.WebElement.equals
Did this instead of documenting webdriver version
=> feat(element): equals

lib/selenium-webdriver/locators.js, website/docgen/dgeni-config.js
…`className`, `css`, `id`, `name`, `partialLinkText`, and `xpath`
=> docs(locators): protractor stye docs for `className`, `css`, `id`, `name`, `partialLinkText`, and `xpath`

lib/element.js, spec/basic/elements_spec.js
Follow up from https://github.com/angular/protractor/pull/3056
=> fix(protractor): isPresent() should work with out of bounds errors

gulpfile.js, lib/configParser.ts, lib/exitCodes.ts, lib/logger2.ts, lib/taskLogger.ts, package.json, spec/unit/configParser_test.js, spec/unit/logger_test.js, typings.json
- add log levels info, debug, warn, error
- add logging to file, console, both, or none
- add color and some log formatting
- fix error logging
=> feat(logger): improve logging methods

lib/driverProviders/driverProvider.ts, lib/driverProviders/local.ts
=> fix(local): close browsers using interactive testing

config.json, package.json, spec/ciFullConf.js, spec/ciNg2Conf.js, spec/ciSmokeConf.js
Updating versions of the following dependencies:
```
Selenium-webdriver : 2.53.1
selenium: 2.53.0
iedriver: 2.53.1
```
Referenced on #3167, #3154
=> deps: Updating selenium-webdriver + selenium + iedriver

website/gulpfile.js, website/js/api-controller.js, website/js/directives.js, website/package.json
Hey guys, I was looking on the project and I found a deprecated dependency for the website/, so I updated in package.json and gulpfile.js, also, I found some lines without semicolon and I updated too.
=> Refactor: Removing deprecated dependency and adding missing semicolon.

package.json
closes #3173, closes #3167, closes #3058
=> deps(selenium): upgrade to selenium-webdriver 2.53.2

docs/plugins.md
=> [docs] fixing an outdated info in plugins section

lib/browser.ts, lib/ptor.ts, lib/runner.ts
* clean up comments and clang issues
* move unnecessary exports to the browser class
=> chore(browser): clean up types

lib/browser.ts
adding parameter types and return types to functions that are defined in runner.
=> chore(browser): add function types

lib/configParser.ts, lib/exitCodes.ts, spec/unit/configParser_test.js
=> chore(config): use thrown error stack trace for ConfigError

package.json
=> dep(webdrivermanager): upgrade to 10.1.0

lib/browser.ts, lib/element.ts, lib/expectedConditions.ts, lib/locators.ts, lib/selenium-webdriver/locators.js, lib/selenium-webdriver/webdriver.js, website/docgen/dgeni-config.js
- Fix order for website (see #3163. Does not include $ / $$)
- Replace @return with @returns so descriptions will appear
=> chore(website): fix website for items to appear properly

lib/util.ts
=> fix(util): check stack exists before filtering the stack trace

lib/selenium-webdriver/webdriver.js
=> fix(website): edit getText JSDoc for shortDescription

lib/browser.ts, lib/expectedConditions.ts, lib/ptor.ts, scripts/typings_tests/test_fail_expected_conditions.ts, scripts/typings_tests/test_pass.ts
- after investigation, ExpectedConditions_ as a class name does not appear on the website
- changed ExpectedConditions_ to ProtractorExpectedConditions
- added an @alias so ProtractorExpectedConditions shows up as ExpectedConditions
=> chore(expectedConditions): change the class name to appear on the website

gulpfile.js, scripts/typings_tests/test_fail_browser.ts, scripts/typings_tests/test_fail_by.ts, scripts/typings_tests/test_fail_elements.ts, scripts/typings_tests/test_fail_expected_conditions.ts, scripts/typings_tests/test_pass.ts
=> chore(test): fix typings test with an ambient typings declaration file

README.md
=> docs(readme): add testapp dependency installation instructions

README.md
=> docs(readme): update protractor version

lib/browser.ts, lib/element.ts
I got some of them. I'm not sure if I got them all, though.
Ref #3360
R: @cnishina
=> docs(browser): replace protractor refs

lib/ptor.ts
=> fix(types): add webdriver.promise and webdriver.WebElement to namespace

lib/ptor.ts
=> fix(protractor): export class definitions under the protractor namespace

lib/launcher.ts
=> fix(launcher): output uncaught exception error

lib/element.ts
=> fix(element): set variables to public in constructor

lib/browser.ts
=> docs(browser): getLocationAbsUrl returns a promise to a string

lib/config.ts
=> fix(config): fix interface for functions such as onPrepare

spec/ciFullConf.js, spec/ciNg2Conf.js, spec/ciSmokeConf.js
- fix flakes coming from sauce labs timeouts
=> chore(ci): increase test times for ci

lib/browser.ts
Updated the outdated example of `debugger` !
=> updated browser.debugger example in JS doc

docs/debugging.md
updated `browser.debugger` and added VSCode setup for debugging protractor!
=> Updated debugging.md

exampleTypescript/package.json, exampleTypescript/tsconfig.json
=> chore(exampleTypescript): use a tmp folder for compiled files

spec/dependencyTest/protractor_spec.js, spec/plugins/specs/bigger_spec.js, spec/plugins/specs/fail_spec.js
- JavaScript file should use 'var' and not 'let'
- Plugin tests should use '__BASIC_PLUGIN_RAN_SETUP'
=> chore(tests): fixes to test suite

exampleTypescript/tsconfig.json, gulpfile.js, spec/install/tsconfig.json
=> fix(types): remove relative path used for @types/node and @types/jasmine

lib/browser.ts, lib/clientsidescripts.js
On top of https://github.com/angular/protractor/pull/3546
=> chore(scripts): move protractor base mock module to clientSideScripts

docs/browser-setup.md
Problem: Broken link in `browser-setup.md` doc
Solution: Fix the link address
=> Fix link to config.ts file

lib/element.ts
=> docs(website): fix markdown parsing bug

lib/element.ts
=> fix(types): Make element.then()'s signature more broad.

gulpfile.js
- will allow circle ci to do a format check
=> chore(gulpfile): remove format from install

lib/element.ts
Another approach to #3721. The alternative is #3726.
=> chore(types): make TS think that Element[Array]Finder extends WebElement

lib/browser.ts
=> chore(browser): fix typings for getCapabilities

lib/element.ts, website/test/e2e/api_spec.js
Fixes https://github.com/angular/protractor/issues/3709
=> docs(website): document '$' and '$$'

.jshintrc, gulpfile.js, lib/driverProviders/direct.ts, lib/driverProviders/local.ts, lib/element.ts, lib/exitCodes.ts, spec/basic/elements_spec.js, spec/basic/lib_spec.js, spec/basic/locators_spec.js, spec/basic/mockmodule_spec.js, spec/basic/navigation_spec.js, spec/basic/polling_spec.js, spec/basic/synchronize_spec.js, spec/errorTest/baseCase/error_spec.js, spec/interaction/interaction_spec.js, spec/onCleanUpNoReturnValueConf.js, spec/plugins/skipStabilityConf.js, spec/plugins/waitForAngularConf.js, spec/unit/configParser_test.js, spec/unit/driverProviders/direct_test.js, spec/unit/driverProviders/local_test.js, spec/unit/logger_test.js, spec/unit/runner_test.js
- update gulpfile to use .jshintrc
- address jshint errors in specs
=> chore(cleanup): jshint cleanup for spec

lib/element.ts
- change comments to not be in JSDoc format
- revert change
=> fix(revert): element(locator).then reverted.

.gitignore, lib/element.ts
**docs(element): fix docs for $$**
Also:
- added .DS_Store to .gitignore
=> docs(element): fix docs for $$

docs/faq.md, website/index.html
"end-to-end" is a noun phrase and therefore should be hyphenated.
=> Fixes grammar issue in page title

docs/locators.md
**docs(locators): add $$ shortcut to locators.md**
=> docs(locators): add $$ shortcut to locators.md

spec/basic/elements_spec.js
Update test after looking into #1600
=> tests(element): We can now pass elements to executeScript, update test.

lib/frameworks/jasmine.js
=> fix(jasmine): Return the full test name in Jasmine test results.

lib/driverProviders/direct.ts, lib/driverProviders/local.ts
=> chore(error): improve error message for local and direct driver providers

lib/driverProviders/direct.ts
https://github.com/angular/protractor/pull/3861 fixed tslint but not `gulp format:enforce` (sigh)
=> chore(lint): fix gulp format:enforce

lib/element.ts
This is a fix for issue https://github.com/angular/protractor/issues/3831
=> fix(element): Fix typing of ElementFinder.then

docs/faq.md, lib/selenium-webdriver/webdriver.js, website/docgen/dgeni-config.js, website/docgen/processors/add-links.js, website/docgen/spec/add-links-spec.js, website/test/e2e/api_spec.js
=> docs(actions): Improve documentation around drag and drop.

lib/element.ts
Now, in the key of ***fun*** name!
(the actual commit has a somewhat more helpful description)
=> Possibly the greatest PR that Craig has ever seen

lib/browser.ts, lib/element.ts
=> fix(isElementPresent): for un-wrapped `WebElement`s, `browser.isElementPresent` was broken

lib/config.ts, lib/driverProviders/sauce.ts
=> fix(sauce): **breaking change** Remove redundant sauceAgent setting.

spec/errorTest/getMultiCapabilitiesConf.js
=> Broke master in a lame way. 

docs/frameworks.md, lib/config.ts
=> chore(cleanup): remove cucumber since it is a custom framework

spec/basic/expected_conditions_spec.js
Workaround for chromedriver-1500 https://bugs.chromium.org/p/chromedriver/issues/detail?id=1500
=> fix(ci): Sleep a small amount before closing the alert.

lib/driverProviders/direct.ts, lib/driverProviders/local.ts, scripts/unit_test.json, spec/unit/driverProviders/direct_test.js, spec/unit/driverProviders/local_test.js
=> chore(local): if no local drivers provided in config, use update-config.json

package.json
- use @types/selenium-webdriver ~2.53.39
- fix for tslint
closes #3939
=> deps(update): update tslint and @types/selenium-webdriver

circle.yml
A little bit excessive, but this will really help debugging issues with
Blocking Proxy.
=> chore(ci): Log tcp traffic on CircleCI

lib/element.ts
Add some generics to ElementArrayFinder methods.
=> chore(types): make ElementArrayFinder more generic

lib/plugins.ts
Based off https://github.com/angular/protractor/pull/3738
=> chore(types): better types for ProtractorPlugin

DEVELOPER.md
**docs(developers): add fixes and links to DEVELOPER.md**
=> docs(developers): add fixes and links to DEVELOPER.md

lib/element.ts
**docs(element): fix minor typo in element.ts**
=> docs(element): fix minor typo in element.ts

docs/timeouts.md
=> Updated documentation for ignoreSynchronization

.gitignore, .npmignore, circle.yml, package.json, spec/directConnectConf.js, spec/install/package.json
Disable Firefox directConnect test until #4253 is fixed.
=> chore(ci): Disable FF directConnect test temporarily to unblock CI

docs/api-overview.md, exampleTypescript/asyncAwait/README.md
**docs(developers): add fixes and links to api-overview.md and asyncAwait/README.md**
=> docs(developers): add fixes and links to api-overview.md and asyncAwait/README.md

docs/plugins.md
**docs(plugins) add protractor-numerator plugin to plugins.md**
=> docs(plugins) add protractor-numerator plugin to plugins.md

docs/frameworks.md
Update wrong usage of the cucumber dry run option.
=> docs(frameworks) update cucumber dry run option

lib/index.ts
by.cssContainingText returns a ProtractorLocator, but Locator couldn't be imported in a TS file.
=> Export Locator

package.json, scripts/test.js
Also uncomment the tests.
Fixes #4448
=> Update to the latest blocking proxy

lib/clientsidescripts.js
=> Update clientsidescripts.js to fix waitForAngular where whenStable calls back true

README.md
**This pull request adds link to DEVELOPER.md in README.md**
=> docs(readme) add link to DEVELOPER.md

README.md
This reverts commit 9027274ba66f869bc3269eaf268247eaaaa7d3df.
=> Revert "Changes "Angular" to "Angular 2" (#4683)"

CHANGELOG.md
Pull Request for Issue #4770
https://github.com/angular/protractor/issues/4770
=> updated CHANGELOG based on sauceSeleniumAddress and sauceSeleniumUseHttp

spec/errorTest/slowHttpAndTimeoutConf.js, testapp/package-lock.json
=> fix(test): fix async tests

.travis.yml, package-lock.json
=> Update Node versions

lib/debugger.ts, lib/driverProviders/driverProvider.ts, lib/driverProviders/mock.ts, package-lock.json, package.json, scripts/errorTest.js, spec/ng2/async_spec.js
1. Update webdriver_js_extender to 2.0
2. Update typing of selenium webdriver to 3.0.10
3. Fix typing issues.
=> deps(webdriver_js_extender): update webdriver_js_extender to 2.0

lib/browser.ts
Changing return type of browser.navigate() to be Navigation instead of any.
=> fix(browser): browser.navigate() return type.

lib/index.ts
=> Fix incorrect exports in index.ts
