angular/protractor

lib/element.js
lib/protractor.js

Before, the documentation for the global instances of $ and $$ was where the
documentation for the chaining of $ and $$ should have been, and the
documentation for chaining was no where.  This fixes that.
Closes issue #1740.

chore(docs): document $ and $$ better

---

lib/plugins.js
lib/runner.js
plugins/README.md
scripts/test.js
spec/errorTest/pluginsFailingConf.js
spec/plugins/fail_spec.js
spec/plugins/failing_plugin.js
spec/plugins/test_plugin.js
spec/pluginsBasicConf.js

Additionally, add some tests to make sure that plugins can fail properly.
Closes #1842

feat(plugins): add postTest hook for plugins

---

spec/ciConf.js
spec/smokeConf.js

Also, update the version of selenium webdriver to 2.44 (the latest
that sauce labs provides) for the smoke tests.

chore(ci): bump to test against chrome 40

---

CHANGELOG.md
package.json

The next release will be a major version bump because we've made
two breaking changes:
- remove the deprecated `chromeOnly` config option
- remove the `then` function from `element(by.foo)`

chore(release): version bump and changelog for 2.0.0

---

docs/plugins.md
website/package.json

Also, change the `npm run` commands to use gulp - they're
smart enough to grab the right thing now.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/angular/protractor/2285)

chore(website): fix links in plugins docs

---

scripts/sauce_connect_setup.sh

Bump from 4.3.7 to latest 4.3.11.

chore(ci): update version of sauce connect

---

lib/debugger/debuggerCommons.js
lib/driverProviders/direct.js
lib/protractor.js
package.json

Along with it, update `jasminewd2` to avoid situations where the
control flow gets locked up and hangs.
Potential Breaking Change:
This is passing all existing Protractor tests, but there is a
possibility that the changes to the control flow will cause some
test flows to hang. If this causes issues, please revisit your
use of functions affecting the control flow, such as
`flow.execute`.

chore(dependencies): update selenium-webdriver to 2.47.1

---

lib/clientsidescripts.js
lib/protractor.js
lib/runner.js
spec/angular2Conf.js
spec/ng2/async_spec.js

Use Angular2's testability API, if present, when waiting
for stability or loading a page.
Closes #2396

feat(lib): add support for waiting for angular2

---

lib/clientsidescripts.js

This bug was introduced when by.exactRepeater was
Discovered while investigating issue #2365

fix(ng-repeat): properly detect the end of an ng-repeat-start block

---

website/js/api-controller.js
website/js/directives.js
website/js/shared.js
website/partials/api.html
website/partials/ptor-function-list.html
website/test/unit/api-controller-spec.js

chore(website): fix parsing in function list

---

.travis.yml
docs/referenceConf.js
docs/server-setup.md
lib/driverProviders/browserstack.js
lib/runner.js
scripts/browserstack_local_setup.sh
scripts/test_on_travis.sh
scripts/testonsauce.sh
scripts/travis_setup.sh
spec/ciBStackConf.js

Also added BrowserStack to CI
Closes #1013

feat(driver providers): Add BrowserStack support.

---

docs/referenceConf.js
lib/cli.js
lib/configParser.js
lib/driverProviders/attachSession.js
lib/runner.js
scripts/attachSession.js
scripts/test.js
spec/attachSession.js
spec/attachSessionProvider/attachSession_spec.js

Attaching an existing selenium browser session to protractor rather than always creating new one. The session can be passed into the config file as a string via the `sessionId`.

feat(attachSession): attach protractor to existing webdriver session

---

gulpfile.js
lib/taskRunner.ts
lib/taskScheduler.ts

child_process.spawn with `{stdio: inherit}` was not printing to console.

chore(typescript): fix `gulp tsc` to log to console

---

bin/webdriver-manager
lib/driverProviders/direct.js
lib/driverProviders/local.js

The `config.json` has the default versions that `webdriver-manager` uses to download the selenium server jar, internet explorer driver, and chrome driver. This can now be overridden by the `versions.standalone`, `versions.chrome`, and `versions.ie` options. Below describes the new features:
```
webdriver-manager update --versions.chrome=2.19 --versions.standalone=2.51.0 --versions.ie=2.51.0 --ie32
```
Note that either `--ie32`  or `--ie` option is still required to download the internet explorer driver. Also, the `--ie32` overrides the `--ie` option and will only download the 32-bit version.
```
webdriver-manager start --versions.chrome=2.19 --versions.standalone=2.51.0
seleniumProcess.pid: 40388
18:40:11.657 INFO - Launching a standalone Selenium Server
Setting system property …
```

feat(webdriver): add support for custom versions for selenium chrome, and ie driver

---

lib/plugins.js
lib/protractor.js
spec/plugins/skipStabilityConf.js
spec/plugins/specs/skip_stability_spec.js

This allows plugins to turn Protractor's default synchronization on and
off as needed.

feat(plugins) Calculate skipAngularStability dynamically.

---

bin/webdriver-manager

Ignoring SSL should also not reject unauthorized per https://github.com/request/request/issues/1777.
Closes #3035.

chore(fix): add reject unauthorized to request for webdriver

---

lib/protractor.js
scripts/test.js

Trying to use the debug label for window.name fails for versions
of angular older than 1.2.24. See #3115

fix(bootstrap): fix bootstrap for older versions of angular

---

lib/configParser.ts
spec/unit/configParser_test.js

Cucumber allows line numbers to be passed in the filename in the
form of `features/some.feature:42`. Glob expanding that results in
an empty array and nothing being passed to the framework runner.
This change checks for glob magic characters and only tries expanding
it if found. Otherwise it just passes the filename verbatim.
This was previously handled in [#2445] by stripping the line number
first, but this is a more generic (non-cucumber) way to do it.
Glob needed to be upgraded for this which resulted in a weird [npm 3
bug](https://github.com/npm/npm/issues/10637). Removing the rimraf
package resolved this. It was only used to generate documentation
which itself was removed a while ago.

chore(configParser): allow non-glob file pattern

---

website/docgen/processors/add-links.js
website/docgen/spec/add-links-spec.js

This fixes #3170. The doc "view source" links are still pointing to `.js` files. This changes the extension to `.ts` (which should be all right given the recent js -> ts switchover. 
This [test](https://github.com/angular/protractor/blob/master/website/test/e2e/api_spec.js#L101) is failing for me locally, but also fails when I run it against master. I'll investigate more but I don't think it is affected by my changes.

fix(docs): Change extension for docs links to .ts

---

lib/launcher.ts

Fix for #3191
Since the rewrite to typescript the getMultiCapabilities promise configuration did not resolve.
This fix will resolve the promise like it used to before the rewrite

Fix Configuration option getMultiCapabilities when configured as a promise.

---

lib/element.ts

docs(element): Clean up return types for .each() and .then()

---

lib/browser.ts
lib/configParser.ts
lib/driverProviders/driverProvider.ts
lib/element.ts
lib/expectedConditions.ts
lib/globals.d.ts
lib/ptor.ts
lib/runner.ts
spec/basic/expected_conditions_spec.js

rename protractor to browser and add a protractor namespace
* added wrapDriver method from the browser.ts and ExpectedConditions
* added a new instance of ExpectedConditions to the protractor namespace
* imported selenium webdriver ActionSequence, Key, Command, and CommandName to the protractor namespace
* added promise object to the browser class

chore(typings): rename protractor to browser and add a protractor namespace

---

lib/expectedConditions.ts
spec/basic/expected_conditions_spec.js

Added a new feature UrlIs and UrlContains. Tests have passed and all check is done from my side.
happy to change if anything is needed.

[feature] Adding urlIs and urlContains to expectedConditions class

---

lib/browser.ts

Currently protractor opens 'data:text/html' page on Edge browser on test start for angular websites.
Edge redirects 'data:text/html' to an error page 'Thats odd: Microsoft Edge cant find this page' with url 'ms-appx-web://microsoft.microsoftedge/assets/errorpages/unknownprotocol.htm#data:text/html,<html></html>'. Run/Inject javascript on this page sometimes returns 'Javascript execution context no longer exists' error.
Using 'about:blank' does not show this page.

Use resetUrl about:blank for MicrosoftEdge

---

lib/launcher.ts

fix for tsc error: "Argument of type 'Function' is not assignable to parameter"

chore(launcher): clean up multicapabilities typing error

---

gulpfile.js
lib/browser.ts
lib/element.ts
lib/locators.ts

- add 'gulp types' to output index.d.ts
- some clean up for functions to use fat arrow
- clang clean up

chore(types): add function types to element and locators

---

gulpfile.js
lib/browser.ts
lib/element.ts
lib/expectedConditions.ts
lib/globals.d.ts
lib/locators.ts
lib/ptor.ts

- add element.ts to the gulp task for 'gulp types'
- clang clean up
- separate out selenium-webdriver types and extend them in protractor
- remove webdriver types for index.d.ts file

chore(types): add in types inherited from selenium-webdriver

---

lib/cli.ts

This is no longer necessary in the latest version of selenium-webdriver.
Without this change, `--capabilities.chromeOptions.binary` will do nothing,
for example.
Closes #3290

fix(config): do not flatten capabilities

---

gulpfile.js
scripts/typings_tests/test_fail_browser.ts
scripts/typings_tests/test_fail_by.ts
scripts/typings_tests/test_fail_elements.ts
scripts/typings_tests/test_fail_expected_conditions.ts
scripts/typings_tests/test_pass.ts
scripts/typings_tests/test_typings.js

- after investigation, variables in the namespace cannot be assigned a value
- types will require import of the classes and then setting the value from global
```
import {Browser} from 'protractor';
var browser: Browser = global['browser'];
```

chore(typings): remove ptor from gulp types

---

globals.ts
gulpfile.js
tsconfig.json

- fixes Exported external package typings file is not a module
- allows for users to `import {browser,element,by,$,$$,ExpectedConditions} from 'protractor/globals';`

chore(types): fix import of package.json typings

---

gulpfile.js
lib/config.ts
lib/configParser.ts
lib/driverProviders/attachSession.ts
lib/driverProviders/browserStack.ts
lib/driverProviders/direct.ts
lib/driverProviders/driverProvider.ts
lib/driverProviders/hosted.ts
lib/driverProviders/local.ts
lib/driverProviders/mock.ts
lib/driverProviders/sauce.ts
lib/launcher.ts
lib/logger.ts
lib/logger2.ts
lib/runner.ts
lib/taskRunner.ts
lib/taskScheduler.ts

- split out config interface from configParser
- add comments from docs/referenceConf.js to lib/config.ts
- allows for users to `import {Config} from 'protractor';`

chore(types): split out config interface from configParser

---

gulpfile.js
lib/browser.ts
lib/cli.ts
lib/configParser.ts
lib/driverProviders/attachSession.ts
lib/driverProviders/browserStack.ts
lib/driverProviders/direct.ts
lib/driverProviders/local.ts
lib/element.ts
lib/exitCodes.ts
lib/expectedConditions.ts
lib/globals.d.ts
lib/launcher.ts
lib/locators.ts
lib/ptor.ts
lib/util.ts

- removed `gulp clang` from gulp file
- added `gulp format` - automatically clang formats typescript
- added `gulp format:enforce` - shows verbose clang errors
- updated the gulp tasks to use `gulp format` instead of the `gulp clang` task
- ran `gulp format` to clean up files

chore(cleanup): clean up with clang issues

---

lib/selenium-webdriver/locators.js
lib/selenium-webdriver/webdriver.js

- Remove getInnerHtml and getOuterHtml from inherited WebElement docs.
- Remove some goog.provide. Only one is required to build the website.

chore(website): clean up documentation

---

docs/plugins.md
exampleTypescript/plugins.ts
gulpfile.js
lib/plugins.ts

fix(types): output plugin typings

---

CONTRIBUTING.md

This could be confusing for first-time contributors.

docs(CONTRIBUTING.md): fix typo (submitted --> merged)

---

lib/browser.ts
lib/clientsidescripts.js
spec/hybrid/async_spec.js

Needed for angular2 after rc2
Basically, we've been testing for if an app is ng1 or ng2 based on if `window.getAngularTestability` exists.  After rc2, hybrid apps will have `window.getAngularTestability` set, so this will no longer work.

fix(hybrid): add flag specifying that an app is an ng1/ng2 hybrid

---

lib/driverProviders/browserStack.ts

The `end()` method on `https.request` object needs to be called.

Fix 'mark test suite as failed/passed on BrowserStack': fixes #3256

---

lib/plugins.ts

There is no need to loop through all plugins, once we have found one the wants to "skipAngularStability".
(Theoretically, this is a performance improvement :stuck_out_tongue: )

refactor(plugins): short-circuit `skipAngularStability` check

---

lib/config.ts
lib/driverProviders/sauce.ts
lib/globals.d.ts

fix(sauce): sauceAgent passed incorrectly to sauce node module

---

gulpfile.js
lib/globals.d.ts
lib/plugins.ts

- Changes for typings to pass test suite.
- Remove the type for HttpProxyAgent and set it to any.
- Uses the namespace Q instead of the module q. Changes have been applied to the plugins file.
- Change to gulpfile to use a reference path for ambient and main typings files.

chore(types): fixes for ambient and main typings files

---

globals.ts
gulpfile.js
lib/browser.ts
lib/element.ts
lib/main.ts
lib/ptor.ts
lib/runner.ts
scripts/test.js
spec/dependencyTest/protractor_spec.js
spec/install/.gitignore
spec/install/conf.ts
spec/install/javascript_spec.js
spec/install/package.json
spec/install/test.js
spec/install/tsconfig.json
spec/install/typescript_spec.ts
spec/install/typings.json
tsconfig.json

- rename to ProtractorBrowser to be able to export selenium-webdriver Browser as Browser
- export all selenium-webdriver items and subfolders in ptor
- update dependency tests for selenium
- add tests when protractor is installed
closes #3427 
closes #2092

fix(export): export selenium-webdriver

---

lib/util.ts

- Fix argument of type 'string | Error' is not assignable to parameter of type 'string'.

chore(util): remove argument type for err

---

docs/plugins.md
lib/plugins.ts
lib/runner.ts
spec/plugins/plugins/basic_plugin.js
spec/plugins/specs/smoke_spec.js

Allows plugins to access framework-specific variables/funtions
A feature that seemed like it would be useful for some internal google users

feat(plugins): support onPrepare in plugins

---

exampleTypescript/package.json
gulpfile.js
lib/browser.ts
lib/element.ts
lib/globals.d.ts
lib/locators.ts
spec/install/package.json
spec/install/typings.json
tsconfig.json
typings/README.md
typings/globals/selenium-webdriver/index.d.ts
typings/index.d.ts

- temporarily add typings for selenium-webdriver.d.ts
- include selenium-webdriver dependency to built/index.d.ts
- add webdriver typings to locators
- update example and spec/install to not use typings.json
- spec test updated to get the tsc test to pass
- includes clang formatting fixes

chore(types): webdriver typings for locators

---

lib/frameworks/mocha.js
spec/mocha/lib_spec.js

Fixes #3045. Since mocha 2.4.1, we should be wrapping global.it.only.

fix(mocha): Wrap it.only with the selenium adapter

---

exampleTypescript/package.json
gulpfile.js
lib/browser.ts
lib/element.ts
lib/globals.d.ts
package.json
spec/install/package.json
tsconfig.json

- include node and jasmine dependency to built/index.d.ts
- update example and spec/install to not need @types/jasmine and @types/node to install
- added an interface in globals for Error to include a code and stack
- improve webdriver typings to elements

chore(types): webdriver typings for elements and browser

---

.gitignore
lib/browser.ts
lib/debugger/clients/wddebugger.js

There's still an issue when calling browser.pause() multiple times in the same test - the other pause statements are ignored. But it no longer exits due to the port being in use. Pausing in multiple tests also works now.

fix(debugger): Fix issues when calling pause() multiple times (#3501)

---

lib/frameworks/jasmine.js
package.json

Fixes #3505 and #2790, which is caused by JasmineWd and Protractor using different
controlflow instances

fix(jasmine): Pass control flow to JasmineWd

---

lib/launcher.ts
spec/mocha/lib_spec.js

Fixes #3522. Also fix the mocha spec to stop yelling at us about ES6
arrow functions.

fix(logger): Set the log level based on the config at startup

---

gulpfile.js
package.json

Previously, the version check would say that 5.2 was less than 4.3.
Fix by using semver.

chore(build): fix version check in gulpfile

---

exampleTypescript/.gitignore
exampleTypescript/conf.ts
gulpfile.js
lib/browser.ts
lib/element.ts
lib/globals.d.ts
lib/index.d.ts
lib/locators.ts

- fix exampleTypescript to have noGlobals
- change the exampleTypescript tsconfig.json to include @types
- alias promise as wdpromise everywhere
- refactor gulpfile task 'types' to use multiple files from tsc
- add browser method types applied from webdriver
this closes #3430, closes #3477, and closes #3500

chore(types): clean up TypeScript support

---

lib/selenium-webdriver/webdriver.js

In getAttibute function documentation :
`expect(foo.getAttribute(class))...` was written.
This got me confused when getting a class attribute.
I just added quotes around the class word showing class as a string
and not a variable.
Close #3619

docs(webdriver): Add missing quotes in getAttribute doc.

---

lib/expectedConditions.ts

MSEdge does not properly remove newlines, which causes false negatives when using `textToBePresentInElement()`

fix(conditions) Explicitly remove newlines from getText()

---

lib/ptor.ts
package.json

This PR should fail until https://github.com/DefinitelyTyped/DefinitelyTyped/pull/11657 is merged and published to `@types`.

chore(ptor): properly export typings on ptor

---

lib/config.ts
lib/launcher.ts

fix(launcher): Ignore uncaught exceptions from webdriver.

---

lib/browser.ts
lib/debugger.ts
lib/debugger/modes/commandRepl.js
lib/frameworks/explorer.js
lib/runner.ts

This pulls the debugger out of browser.ts and into a separate module. This is the first step in porting the debugger to typescript and adding unit testing around it.

Refactor the debugger out of browser.ts

---

lib/runner.ts
spec/install/.gitignore
spec/install/browserjs_spec.js
spec/install/browserts_spec.ts
spec/install/conf.ts
spec/install/test.js
spec/install/typescript_conf.ts

fix(restart): typescript fix for browser.restart

---

lib/browser.ts

Currently. `all` is marked as optional. It means `all` can be `undefined`, which isn't true. For this reason, it's impossible now to use `element.all` with TS 2.x if `strictNullChecks` is `true`. Simple code like
```
element.all(by.css('.info'))
```
leads to an error: `Object is possibly 'undefined'`.

fix(types): fix types for element.all(...)

---

lib/browser.ts
lib/config.ts
lib/configParser.ts
lib/runner.ts
spec/hybrid/async_spec.js
spec/hybridConf.js

Response to @juliemr's comments on https://github.com/angular/protractor/commit/71532f055c720b533fbf9dab2b3100b657966da6

feat(hybrid): set ng12hybrid flag in the config

---

.clang-format

Does anybody use an 80x25 hardware text-mode terminal to edit this code? Why is this value so low? It doesn't help the readability at all.
The Angular 2 project has [has](https://github.com/angular/angular/blob/master/.clang-format) `ColumnLimit: 100`.

chore(clang-format): increase ColumnLimit to 100

---

docs/browser-setup.md

`require('phantomjs')` is not working

use phantomjs-prebuilt

---

lib/config.ts
lib/frameworks/jasmine.js

This adds handling of `random` and `seed` options in `jasmineNodeOpts` and allows to run specs in random order. The descriptions for both options are taken from Jasmine [docs](http://jasmine.github.io/2.4/node.html#section-14).
- Reasons for adopting new feature
Running specs in random order is usually preferable, as it ensures that the tests don't depend on each other and don't leak unwanted changes.
- Is this a breaking change? (How will this affect existing functionality)
Nope.

feat(config): Add 'random' and 'seed' Jasmine config options

---

lib/config.ts
lib/index.ts
lib/runner.ts
spec/basic/restart_spec.js

Because globals are set in the runner, they may be undefined at import time. Also, the `browser` global object will change if `browser.reset()` is called. By making these globals exported as properties, they will be resolved dynamically. This also fixes issues importing protractor in config files written in typescript, since the globals are resolved at call time instead of at import time.
Note that until the Runner calls `setupGlobals_`, these exports will be undefined. That's just the nature of these objects, though, and the global objects have the same behavior.

fix(globals): Resolve exported globals dynamically.

---

lib/browser.ts
lib/config.ts
lib/element.ts
lib/plugins.ts

Some code reformatting happened here because of changing `ColumnLimit` in `.clang-format`. I can extract it to a separate PR if needed. The main idea of this PR is to use the type definitions for the `selenium-webdriver` module and make the compiler infer better types for the members of the `Plugins` class.

chore(types): make plugins.ts more strongly-typed

---

docs/faq.md
docs/timeouts.md
lib/browser.ts
scripts/test.js

Also changed the way headers work in the timeouts doc, so now the error message has a direct link to the right spot.

docs(timeout): Update timeout error message

---

lib/element.ts
spec/basic/restart_spec.js

Fixes #3696. Also clean up the restart spec test.

cleanup(types): Fix webelement.then() return type.

---

lib/cli.ts
testapp/scripts/web-server.js

`path.join` does not account for absolute paths like `path.resolve` does.  This
is not a problem in this case but could be in the future

chore(refactor): prefer `path.resolve`

---

lib/browser.ts
lib/expectedConditions.ts
lib/runner.ts
scripts/sauce_connect_setup.sh
spec/basic/expected_conditions_spec.js
spec/basic/handling_spec.js
spec/dependencyTest/protractor_spec.js

fix(ExpectedConditions): non-static ExpectedConditions for browser

---

exampleTypescript/package.json
package.json
spec/install/package.json

- update outdated dependencies
- move @types/jasmine to devDependencies
closes #3792

deps(update): move @types/jasmine to devDependencies

---

package.json
scripts/generate-docs.sh
scripts/testserver.sh
testapp/package.json
website/package.json

- npm start - installs dependencies and starts the testapp
- npm run website - installs dependencies and starts the website
- cleanup testapp package scripts that are not used
- npm run format - shortcut for 'gulp format' for contributors that failed format check test

chore(scripts): clean up package scripts

---

lib/config.ts
lib/driverProviders/local.ts

It's nice to specify how long time the Local DriverProvider waits for the selenium-webdriver server to start.
The Local DriverProvider starts local selenium-webdriver server, and waits for the server in 30,000ms now. That's because `DriverService#start()` of selenium-webdriver/remote has an arg `opt_timeoutMs` default 30,000ms.
30,000ms is almost enough long, but that depends on environment.

Proposal: add seleniumServerStartTimeout in Local DriverProvider

---

lib/config.ts

fixes https://github.com/angular/protractor/issues/3816

fix(config): cucumberOpts.require should be an optional Array of strings

---

spec/basic/elements_spec.js
spec/ciFullConf.js
spec/ciNg2Conf.js
spec/ciSmokeConf.js

This also drops support for Safari 9, which doesn't use safaridriver.

chore(deps): Update Travis Selenium 3.0 and latest browsers

---

lib/element.ts

Using `await myElemFinder` in typescript returns "any" instead of the `ElementFinder[]` type

fix(element): Fix typing of then function

---

circle.yml
gulpfile.js
lib/browser.ts
lib/cli.ts
lib/debugger.ts
lib/driverProviders/attachSession.ts
lib/driverProviders/browserStack.ts
lib/driverProviders/sauce.ts
lib/element.ts
lib/expectedConditions.ts
lib/launcher.ts
lib/locators.ts
lib/plugins.ts
lib/ptor.ts
lib/runner.ts
lib/taskLogger.ts
lib/taskScheduler.ts
package.json
tslint.json

- add gulp task tslint and lint
- update `**/*.ts` with tslint fixes
- update circle.yml to run `gulp lint`
- update `gulp pretest` to run both jshint and tslint

chore(tslint): add tslint to gulpfile

---

lib/driverProviders/index.ts
lib/runner.ts

- builds the driver provider in lib/driverProviders/index instead of lib/runner
closes #1945

chore(driverProviders): add warnings to extra driver provider parameters

---

lib/launcher.ts
scripts/errorTest.js
scripts/test.js
spec/errorTest/getMultiCapabilitiesConf.js

fix(launcher): running getMultiCapabilities should reject on errors

---

lib/breakpointhook.js
lib/browser.ts
lib/debugger.ts
lib/debugger/clients/explorer.js
lib/debugger/clients/wddebugger.js
lib/debugger/debuggerCommons.js
lib/debugger/modes/commandRepl.js
lib/debugger/modes/debuggerRepl.js
lib/frameworks/explorer.js
scripts/test.js

This implementation now relies mostly on promises explicitly,
so the control flow is only used to add one large task to the queue.
This should pave the way for the eventual removal of the control flow,
as well as getting element explorer to work immediately.
Note that there are several missing items and TODOs at the moment:

Refactor element explorer to work with selenium-webdriver 3

---

package.json

Fixes issue #3879 (https://github.com/angular/protractor/issues/3879)
Updating @types/selenium-webdriver dependency to @types/selenium-webdriver@2.53.38 which added back the protractor.Key.chord method.

Update @types/selenium-webdriver dependency

---

scripts/test.js
scripts/test/test_util.js

CircleCI will timeout the test if it doesn't see any output for 10
minutes. When running in CI, we need to inherit stdio so we don't get
killed if the tests run slowly due to timeouts. This will also give us
more info for debugging.

fix(ci): Log test output on CircleCI

---

lib/frameworks/README.md
lib/index.ts

This will allow us to implement `restartBrowserBetweenTests` without the control flow, and in the future maybe add more features users have been asking for.

chore(docs): new framework requirements in Protractor 6.0

---

lib/browser.ts
lib/clientsidescripts.js
lib/config.ts
lib/configParser.ts
lib/runner.ts
scripts/test.js
spec/angular2Conf.js
spec/angular2TimeoutConf.js
spec/driverProviderAttachSessionConf.js
spec/driverProviderLocalConf.js
spec/hybrid/async_spec.js
spec/hybridConf.js
spec/inferRootConf.js
spec/noGlobalsConf.js
spec/unit/configParser_test.js

feat(rootEl): auto-detect the root element better

---

lib/browser.ts
lib/clientsidescripts.js
lib/config.ts
lib/configParser.ts
lib/runner.ts
scripts/test.js
spec/angular2Conf.js
spec/angular2TimeoutConf.js
spec/driverProviderAttachSessionConf.js
spec/driverProviderLocalConf.js
spec/hybrid/async_spec.js
spec/hybridConf.js
spec/inferRootConf.js
spec/noGlobalsConf.js
spec/unit/configParser_test.js

This is a duplicate of https://github.com/angular/protractor/pull/3849 which was accidentally done against the beta branch

feat(rootEl): ***breaking change*** auto-detect the root element better

---

package.json

It's required through webdriver-manager now.

chore(deps): remove adm-zip from dependencies

---

spec/basic/elements_spec.js

With https://github.com/angular/jasminewd/pull/78, jasminewd no longer supports passing deferreds to expect(). Change the test to pass a promise, instead.

fix(spec): Fix failing test

---

lib/clientsidescripts.js

* Currently in Protractor v5 the Angular detection script uses ES6 features like the `let` modifier. 
This can break Protractor on browsers, which doesn't support those statements. 
> See https://saucelabs.com/beta/tests/275f75091dac40a0a3374d29d912caee/commands#11
**Note**: This currently makes Protractor v5 hard to use on older browsers. (On Material 2 we will update browsers)
cc. @sjelin @cnishina

fix: no longer use es6 let statement

---

lib/cli.ts

With reference to this recent [SO question](http://stackoverflow.com/questions/41592870/found-extra-flags-error-in-new-version-of-protractor) , it would be good to display the `--disableChecks` option in the error message thrown in case users have their own custom flags set in the cli.
Users are not aware of this option until they check the changelog, it would help if this is displayed along with the error message thrown in the console itself. 
@cnishina Since you worked on this, any thoughts?

display disableChecks option in extra flags error message

---

lib/selenium-webdriver/webdriver.js

The existing documentation was redundant and confusing.
Closes https://github.com/angular/protractor/issues/3679

chore(docs): cleaned up documentation for `browser.wait`

---

lib/runner.ts

Follow up to https://github.com/angular/protractor/pull/3893.
Part of #3893
I could have just made it a noop I guess but I think it makes sense to actually use it.

chore(frameworks): allow frameworks to call `afterEach`.

---

lib/element.ts
spec/basic/elements_spec.js

Fix for https://github.com/angular/protractor/issues/3812

feat(elements): Add isPresent() to ElementArrayFinder

---

lib/cli.ts
lib/config.ts
lib/driverProviders/driverProvider.ts

chore(blockingproxy): Allow using a pre-existing Blocking Proxy instance

---

circle.yml
lib/driverProviders/direct.ts
spec/ciFullConf.js
spec/ciSmokeConf.js
spec/directConnectConf.js

fix(firefox): Fix directConnect for Firefox 51+

---

lib/driverProviders/local.ts

Fixes #3986. Also warn if jvmArgs isn't an array.

fix(driverProviders): Handle promise rejection when starting selenium

---

lib/driverProviders/local.ts

Fixes CI, that's what I get for not being patient.

fix(driverProviders): Check config in the right place.

---

lib/driverProviders/README.md
lib/driverProviders/attachSession.ts
lib/driverProviders/driverProvider.ts
lib/runner.ts

Wrapping it in a `q` promise is blocking https://github.com/angular/protractor/issues/3899
Closes https://github.com/angular/protractor/issues/3902
Custom frameworks might not make this change but it'll be fine.  It'll only be a
problem in edge cases and they probably weren't returning the right promise
before anyway.

chore(quitDriver): have quitDriver return a webdriver promise directly

---

lib/cli.ts
lib/config.ts
lib/frameworks/README.md
lib/runner.ts
scripts/errorTest.js

Fix for #3978.
Our initial plan to allow setting --disableChecks with an environment variable is insufficient, since the custom framework isn't even require()'d until after the config is parsed. This moves the unknown flag check into the runner, and gives frameworks a way to specify extra flags they accept.

fix(cli): Allow frameworks to specify extra command line flags

---

lib/runner.ts

Closes https://github.com/angular/protractor/issues/3898

chore(runner): wait for debugger using `then` block

---

lib/frameworks/mocha.js

Closes https://github.com/angular/protractor/issues/3985

chore(mocha): refactor to use `selenium-webdriver`'s mocha adapters

---

lib/browser.ts
lib/runner.ts

Also allows `browser.restart` to work when the control flow is disabled, and
fixes it for forked browsers.
Closes https://github.com/angular/protractor/issues/3899 and
https://github.com/angular/protractor/issues/3896

feat(restart): `browser.restart` should return a promise

---

lib/browser.ts
lib/runner.ts

Closes https://github.com/angular/protractor/issues/3900

feat(browser.ready): make `browser.ready` wait for all async setup work

---

lib/browser.ts

This really belonged in https://github.com/angular/protractor/pull/3998 but I guess we all make mistakes

chore(types): types for extended webdriver functions

---

lib/browser.ts
lib/debugger.ts
lib/element.ts
lib/runner.ts

Closes https://github.com/angular/protractor/issues/3903
Asking @cnishina or @mgiambalvo for review since I've asked @juliemr for several lately

chore(wdpromise): prefer `wdpromise.when` to `wdpromise.fulfilled`

---

lib/bpRunner.ts
lib/browser.ts
package.json

Implements #3947. This is the other side of https://github.com/angular/blocking-proxy/pull/21

Replace rootEl with browser.setAngularRoot()

---

lib/browser.ts

feat(browser): chain promises in `browser.get`

---

lib/element.ts
lib/expectedConditions.ts
lib/util.ts
spec/basic/expected_conditions_spec.js

Add error handler `falseIfMissing` to all expected conditions that depend
on the presence of an element.
Expected conditions check the presence of an element before other checks,
but when an element is removed exactly in the moment after the `isPresent`
and before `isDisplayed` in `visibilityOf` the condition used to fail.
This solution does not handle missing elements in (`isEnable`, `isDisplayed`, `isSelected`) and focused only on expected conditions (see
#3972)
This problem was also referenced in
#3578.
Add test cases to reproduce the missing element race conditions possible in
expected condition methods `visibilityOf`, `textToBePresentInElement`,
`textToBePresentInValue` and `elementToBeClickable`.
See failing tests before implementation: …

Issue 3578 expected conditions

---

lib/browser.ts

Closes https://github.com/angular/protractor/issues/3185

chore(browser): deprecate `browser.getLocationAbsUrl()`.

---

lib/browser.ts
lib/element.ts
lib/locators.ts

I decided to address this comment:
https://github.com/angular/protractor/pull/4000#issuecomment-275281836
While doing do I decided to take on this TODO:
https://github.com/angular/protractor/blob/ccf02ab5f1070f0d7124318dc0099252f3c747e2/lib/browser.ts#L38
One possible issue here is that `ProtractorBrowser` only copies over methods, so it doesn't actually
implement `WebDriver`'s interface.  This isn't a problem right now, since `WebDriver`'s interface
only has functions on it.  But it could be a problem in the future.
This is also weird in that `browser instanceof webdriver.WebDriver` is false but TypeScript probably thinks otherwise.  An alternative option would be to do: 
```ts
export class AbstractWebDriver {
actions: typeof WebDriver.prototype.actions;
call: typeof …
```

chore(types): Inherit from webdriver.WebDriver types

---

package.json

- Hot fix for overriding `print` function in `jasmineNodeOpts`
closes #3916

deps(jasmine): update jasmine to ^2.5.3

---

lib/browser.ts
lib/runner.ts

I also fixed a minor issue where `internalRootEl` wasn't being set when blocking proxy was being
used.  I also just cleaned up our internal uses of `this.rootEl`.
Closes https://github.com/angular/protractor/issues/4032

fix(restart): preserve properties like `browser.baseUrl` upon restart

---

lib/bpRunner.ts
lib/config.ts
lib/runner.ts
package.json

This adds two options, both of which are implemented with Blocking
Proxy. --webDriverLogDir will create a readable log with timing
information of webdriver commands in the specified directory.
--highlightDelay will pause before clicking on elements or sending keys.
While paused, the element that's about to be affected will be
highlighted.

feat(debugging): Add webdriver logging and highlight delay

---

scripts/generate-docs.sh

I never ran into the annotation problem @juliemr talked about, so please test this on your local machines

chore(doc-gen): fix the doc gen script

---

lib/browser.ts
lib/runner.ts

Missed in https://github.com/angular/protractor/pull/4037
Also fixed a minor error where the promises implicitly created by setting
`rootEl` and `ignoreSynchronization` weren't getting chained properly.
Also fixed minor (so minor I think it was impossible to trigger) where
browser.plugins_ could be undefined.

fix(restart): preserve waitForAngularEnabled on restart and chain more promises together

---

lib/browser.ts
release.md
scripts/generate-docs.sh
tsconfig.json

Also added the ability to run `generate-docs.sh` against a custom
branch/tag/commit by doing `./scripts/generate-docs.sh branch_name`.  Still
defaults to the version from package.json though.
Also updated release.md to tell people to check that doc generation/the website
is working BEFORE doing a release.  Needing a change in the codebase is more
likely now that we're compiling down to es5 only this one time, and ideally
any changes to the codebase would happen before release.
Also including a minor change in the codebase where we wrap a promise from
blocking proxy in a webdriver promise.  This probably should have been done the
whole time, but is unlikely to matter either way at runtime, since blocking
proxy wouldn't be returning a webdriver promise regardless.  Mostly did I did
this to …

chore(docgen): fix docgen for 5.1

---

lib/driverProviders/sauce.ts

Sauce Labs added HTTPS support several months ago.

Add Sauce Labs HTTPS Support

---

lib/debugger.ts
lib/element.ts
lib/plugins.ts

TypeScript 2.0 has less awesome type inference than 2.1, so we need to be a little more explicit in some cases.

fix(types): Fix types for TS 2.0

---

docs/plugins.md
lib/index.ts
lib/plugins.ts

* Removed redundent information in `/docs/plugins.md`.  Now redirects to
`/lib/plugins.ts`.
* Comment cleanup in `/lib/plugins.ts`
* Export some necessary types in `/lib/index.ts`

chore(docs): Cleanup plugin docs

---

gulpfile.js
package.json
scripts/compile_to_es5.sh
scripts/generate-docs.sh
website/README.md
website/gulpfile.js
website/package.json
website/test/e2e/api_spec.js
website/test/unit/api-controller-spec.js

Also added npm command `compile_to_es5` to make running the website tests easier.

chore(website): fix website tests

---

exampleTypescript/package.json
exampleTypescript/tsconfig.json

This makes some small updates to TS config and TS related deps to allow compilation with the version of TS installed by the example.
I'm still familiarizing myself with the TS ecosystem and the way things should be done, so please let me know if there's a convention that I've missed here.
Issues Resolved
---
Jasmine typing issues (see https://github.com/DefinitelyTyped/DefinitelyTyped/issues/14569 for more details), Pinning the jasmine typings prevents the following compilation error:
```shell
typescript-example-updates ᎒ npm run tsc
> example-typescript@1.0.0 tsc /Users/ntomlin/workspace/protractor/exampleTypescript
> tsc
node_modules/@types/jasmine/index.d.ts(39,52): error TS1005: '=' expected.
npm ERR! Darwin 16.4.0
```
We could also resolve this by pinning the typescript depedency of …

chore(examples): Fix TSC issues with exampleTypescript

---

lib/browser.ts

The `err` object doesn't have the `code` property any more (Selenium Server Standalone 3.3.1 + IEDriver win32 3.3.0), so we need a new way to detect those errors. See #841

fix(navigation): ignore unknown JS errors in IE

---

docs/frameworks.md

Serenity/JS is a new custom framework adapter supporting both Mocha and Cucumber, so it seems useful for the documentation to mention its availability :-)

docs(custom-frameworks): add instructions for Serenity/JS

---

docs/infrastructure.md

Anchor names on Selenium wire protocol wiki page changed, rendering our
links outdated. Fix them.

chore(docs): Update links to Selenium wire protocol

---

lib/cli.ts

This fixes #4196. Verbose was part of the help text in [`describes`](https://github.com/angular/protractor/blob/master/lib/cli.ts#L110) but not in `allowedNames`

fix: Add "verbose" option to allowedNames in cli.ts

---

lib/selenium-webdriver/webdriver.js

There's a bit of confusion about the default behavior of the second parameter for the `browser.wait` function (e.g. https://github.com/angular/protractor/issues/2253). Adding this info to the docs might clear that up
```
browser.wait(EC.textToBePresentInElement($('#foo'), 'Example words'), 5000); // 5 seconds
browser.wait(EC.textToBePresentInElement($('#foo'), 'Example words')); // 30 seconds
```
default time comes from an optional param in user's `protractor.conf.js` file
```
jasmineNodeOpts: {
defaultTimeoutInterval: 30000
}
```
which falls back to the default set in  `lib/configParser.ts` if not set:
```
jasmineNodeOpts: {showColors: true, defaultTimeoutInterval: (30 * 1000)},
```
https://github.com/angular/protractor/blob/bc583321a233453fc2b89472013b2ec3e1d6b6f9/lib/configParser.ts#L37 …

docs(browser.wait): add default browser.wait default

---

lib/cli.ts

This fixes a problem I encountered similar to #4196 - where `stackTrace` is listed as an option but an error is given saying it's an "unknown extra flag"

fix: Add "stackTrace" option to allowedNames in cli.ts

---

DEVELOPER.md

The link to the developer pre-requisites was dead, so I fixed it. I also noticed `release.md` could've used a link, so I added one.

docs(prerequisites,release): fixed dead pre-requisites link & added link to release.md

---

lib/browser.ts

By default, it wasn't returning anything. Now it returns a promise that
resolves to internalAngularAppRoot. Fixes #4233

fix(browser): Fix angularAppRoot() to return a promise

---

lib/cli.ts
lib/config.ts
lib/driverProviders/sauce.ts

Sauce Connect Proxy listens on 4445 port by default for Selenium communications and always uses HTTP protocol instead of HTTPS. It's not rare to run Sauce Connect Proxy locally or inside private network meaning we're forced to use HTTP and `sauceSeleniumAddressProtocol` is the way to customize which protocol to use.
P.S. In case there are no objections, it'd be nice to have a patch release otherwise we're stuck with dirty looking monkey-patching.

feat(saucelabs): Add Sauce Labs protocol customization support

---

lib/cli.ts

Chromedriver requires that certain options always be passed as an array.
Optimist passes --single-option as a string instead of an array which is
invalid. This ensures that we always pass an array, even if a single
option is passed via the cli.
Fixes #4050

fix(cli): Correctly parse list chromeOptions

---

circle.yml
lib/debugger/debuggerCommons.js
package.json

fix(elementexplorer): Use cross-platform safe regexps when setting breakpoints

---

lib/locators.ts

The Protractor documentation says that By.js is inherited from Selenium Webdriver, and the types for that define the function signature for `js` like I have done in this PR.
https://github.com/SeleniumHQ/selenium/blob/master/javascript/node/selenium-webdriver/lib/by.js#L183
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/selenium-webdriver/index.d.ts#L2441

Typings for By.js locator should accept function arguments

---

docs/browser-setup.md

Fixed incorrect example of setting window size with headless Chrome. When `800x600` is used it is ignored. The correct syntax is `800,600`.

docs(browser-support): Fixed incorrect example

---

lib/driverProviders/driverProvider.ts
scripts/test.js

If local driver provider is used, `seleniumAddress` appears in config only after `setupDriverEnv()` is resolved.
Here is an example of the error caused by missing `seleniumAddress` during `bpRunner` start:
```
protractor$ node ./built/cli.js --webDriverLogDir ./ ./spec/driverProviderLocalConf.js
[22:41:26] I/launcher - Running 1 instances of WebDriver
[22:41:26] I/local - Starting selenium standalone server...
[22:41:26] I/BlockingProxy - Starting BlockingProxy with args: --fork,--seleniumAddress,,--logDir,./
[22:41:27] I/local - Selenium standalone server started at http://192.168.43.204:37560/wd/hub
[22:41:27] I/protractor - Starting BP client for http://localhost:38175
[22:41:27] E/launcher - Error: connect ECONNREFUSED 127.0.0.1:80
[22:41:27] E/launcher - WebDriverError: Error: …
```

fix(blockingproxy): Start bpRunner strictly after setupDriverEnv

---

docs/plugins.md

- Adds [ng-apimock](https://github.com/mdasberg/ng-apimock) to the list Community Plugins

Add ng-apimock plugin to Community Plugins

---

lib/selenium-webdriver/webdriver.js

This PR fixes the incorrect example in http://www.protractortest.org/#/api?view=webdriver.WebElement.prototype.getCssValue and is related to https://github.com/angular/protractor/issues/4246

docs(website): fix issue 4246

---

lib/config.ts
lib/configParser.ts
lib/driverProviders/local.ts
lib/element.ts
lib/locators.ts
spec/basic/actions_spec.js

- Add gecko driver as configuration option to be used in the local
driver provider.
- Nit fixes to use string[] over Array<string> in the configParser.ts.
- Add functionality to addDefaultBinaryLocs_ to use the geckoDriver
value set in the config or to check locally in the
webdriver-manager/selenium folder.
- Fix transpile errors in locator. Missing toString in ProtractorLocator
interface.
- Fix transpile errors in element. Cast wdpromise.Promise<{}> to
wdpromise.Promise<T>.
- xit spec/basic/action_spec.js based on
[selenium-webdriver issue #3693](SeleniumHQ/selenium#3693).
Added a // TODO comment to remove xit when selenium-webdriver resolves issue.
closes #4408 and closes #4411.

fix(local): allow local driver provider to use gecko driver from config

---

lib/selenium-webdriver/locators.js

replaced all `browser.findElement(..)` for `element(..)` to make the API documentation more consistent

fix: fix all locator examples

---

lib/config.ts
lib/driverProviders/sauce.ts

Reverts the change to PR #3868. Protractor should connect to Sauce Labs
via the sauceProxy. This is different than the webDriverProxy. The
webDriverProxy is tied to the browser session where we define where the
traffic will go through.
closes #4405

fix(sauce): bring back sauceProxy as a configuration option

---

docs/plugins.md

Actually a whitespace was missing, but I also thought that `Table of contents` would suite better.

docs(plugins): improve wording

---

lib/runner.ts
package.json

1.Update selenium-webdriverjs and bump version number
2.Solve compatibility problem: new webdriver has a more strict method when setting script timeout. If no script timeout was specified, set timeout to 0.

chore(release): update selenium-webdriverjs and bump version number

---

docs/debugging.md

When the control flow is disabled, `browser.pause()`, `browser.debugger()`, and `browser.enterRepl()` all crash. I couldn't find this documented anywhere other than bug reports, so I've added it to the docs on debugging.

Add docs for debugging with the control flow disabled

---

docs/browser-setup.md

- Added documentation on headless Firefox setup.
- Documented Firefox-specific options.

doc(browser-support) improved Firefox documentation

---

lib/clientsidescripts.js
lib/locators.ts
spec/basic/locators_spec.js

In order to get this working, I had to serialize the regex before
we send it over the wire to the browser.
Since there is no standard way to do this, I took guidance from
a stackoverflow answer, where they call toString on the regex.
Then, on the browser, you use a regex to extract out the text in between
/someregex/
The hard part is to also extract out the modifiers, like i for ignore case.
Anyhow, this approach seems to work, and I have tests to prove it.
This is related to #1360

feat(locators): Add support for regex in cssContainingText

---

docs/page-objects.md

As presented, simply following the example will not run. This presents the Page Object example as a runnable set of spec + Page Object. See #4570
Open possibilities for future work include: carry the initial introduction over into a Page Object. Introduce `world`, etc.

docs(page-objects.md): Refactor the existing Page Object example

---

lib/frameworks/jasmine.js
spec/ts/basic/element_spec.ts
spec/ts/plugin/plugin_spec.ts

fix(jasmine): Update Jasmine to support Node8 async/await
Breaking change for TypeScript:
JasmineWD doesn't know anything about async/await, turns off JasmineWD if control flow was disabled.
It will affect TypeScript tests that are using async/await and
1. miss some await keyword in the test.(Previously, this might cause the
test failed silently and be reported as pass), or
2. use Promise in jasmine expect function
Before
```ts
await expect(getPromise()).toEqual(42);
```
After
```ts
expect(await getPromise()).toEqual(42);
```

fix(Jasmine): Update Jasmine to support Node8 async/await

---

lib/configParser.ts

CoffeeScript lost the hyphen in the module name about 9 months ago, all the new versions are going to be released as coffeescript not the coffee-script

Support the new CoffeeScript module name

---

lib/driverProviders/direct.ts

This change makes the `firefox` capability more closely match `chrome`'s. The `firefox` capability was not looking for `config_.geckoDriver` like `chrome` was, making the `geckoDriver` configuration useless for directConnect and always resulting in an error if the driver wasn't installed in the default location.

fix(direct): Use config's geckoDriver when specified

---

docs/locators.md

A tweak to the documentation to add the Locator by.name.
Amazing tool!
Anibal

fix(website): Site improvement - Locator by.name('field_name')

---

scripts/compile_to_es5.sh

make compile-to-es5 script rely on native es6-promise typing

fix(script): fix compile-to-es5 script

---

docs/page-objects.md

Changed old `getGreeting` to `getGreetingText` so that I could use `getGreeting` for the non-async example of returning the object. As requested https://github.com/angular/protractor/issues/4637.

Add async / await example to page object docs

---

README.md

A recent change in the Readme deleted wording that said `Angular 2`. It makes it sound like no version of Angular will support the `binding` and `model` locators, which is not true. We should re-add the "2" back to make this more clear.
Diff that introduced the issue: https://github.com/angular/protractor/commit/af6afa646cacf5dd2f023561f84429c05f508b77#diff-04c6e90faac2675aa89e2176d2eec7d8

Changes "Angular" to "Angular 2"

---

docs/plugins.md

**docs(plugins) add protractor-cucumber-steps plugin to plugins.md**

docs(plugins) add protractor-cucumber-steps plugin to plugins.md

---

docs/page-objects.md

Fixes #4730 
More info here: https://eslint.org/docs/rules/no-return-await

docs(page_objects): Remove unnecessary "return await"

---

lib/frameworks/jasmine.js

This is an attempt to fix #3952 .
In Jasmine, `beforeAll()` is executed for `pending` tests, but not `disabled` tests. This pr set all tests that are excluded from running to `disabled` so the corresponding `beforeAll()` won't run.

fix(grep): change excluded tests to disabled instead of pending

---

scripts/generate-docs.sh

Ignore generated unstaged files before checking out to new branch; otherwise, the git checkout will fail.

fix(generate-docs): fix generate-docs.sh.

---

lib/plugins.ts

fix(comments): Spelling updates to some of the comments
--Changes:
+ line 43: changed 'onPreare' to 'onPrepare'
+ line 46: changed 'funtions' to 'functions'
+ line 103: fixed punctuation, replaced a period with a semicolon to combine sentence fragments

Spelling updates to comments

---

circle.yml
scripts/test.js
spec/errorTest/slowHttpAndTimeoutConf.js

This patch attempts to fix the continually breaking circleci build. The changes made were:
- Switch to using circleci v2 syntax, as the v1 syntax will be deprecated in August. Also, it permits running the build locally using the `circleci` commandline tool.
- Adjust timeouts on error tests to fail consistently on high-performance machines.
- Correct error formatting on error tests.
Fixes #4810

Fix CircleCI Build

---

lib/driverProviders/local.ts

Always pass webdriver.gecko.driver property to Selenium if set in local
mode
fixes #4501

fix(local): Ensure webdriver.gecko.driver path is passed to Selenium

---

lib/cli.ts
lib/config.ts
lib/driverProviders/browserStack.ts
package-lock.json
package.json
scripts/errorTest.js
spec/driverprovider_test.js

Adding browserstackProxy configuration param to enable users behind proxy to run their tests, example value for this config : "http://proxy.example.com:1234".

feat(driverProvider) Adding browserstackProxy param in BrowserStack driverProvider

---

package-lock.json
package.json

@qiyigg this replaces https://github.com/angular/protractor/pull/4911. All changes should be good now.
Following up on https://github.com/angular/webdriver-js-extender/pull/21, updating `webdriver-js-extender` to version 2.1.0.
Making the 2 new endpoints to send custom commands to the DevTools debugger server (available since ChromeDriver version `2.30` [1]):
* `/chromium/send_command`;
* `/chromium/send_command_and_get_result`.
available for use in protractor.
[1] https://chromium.googlesource.com/chromium/src/+/711de0efbb675bd2a4a28ec47c9194d8e498e600

deps(webdriver_js_extender): update webdriver_js_extender to 2.1

---

.travis.yml
circle.yml
package-lock.json
package.json
scripts/test.js
spec/basic/elements_spec.js
spec/basicConf.js
testapp/package-lock.json

For the basicConf test suite:
- Only run the element_spec test in the Protractor config, we will add
back other specs as we migrate the basicConf off of the control
flow.
- In the Protractor configuration file, set `SELENIUM_PROMISE_MANAGER` to false.
- Refactor to use async / await.
- Refactor `var` to use either `const` or `let`.

chore(test): move element_spec.js off of the control flow

---

spec/basic/handling_spec.js
spec/basicConf.js
spec/ciFullConf.js

@cnishina , could you take a look at this PR, please

chore(test): move handling_spec off of the control flow

---

lib/config.ts

Per the default behavior set in:
https://github.com/angular/protractor/blob/master/lib/driverProviders/sauce.ts#L68-L70
the Sauce OnDemand address will default to ondemand.saucelabs.com:443 unless changed.
The config.ts doc says the default is ondemand.saucelabs.com:80.
This PR simply changes the port number on the config.ts comment.

Update config.ts sauceSeleniumAddress comment to reflect 443 default

---

lib/config.ts
lib/launcher.ts
lib/plugins.ts
lib/runner.ts
lib/taskRunner.ts
spec/ciFullConf.js
spec/ciNg2Conf.js

- changes starting with cleaning up q promises and webdriver promises from plugins

chore(promises): remove q promises and webdriver promises

---

scripts/test.js
spec/basic/expected_conditions_spec.js
spec/plugins/skipStabilityConf.js
spec/plugins/smokeConf.js
spec/plugins/specs/smoke_spec.js

- update to ES6
- fix the expected conditions to await when the browser is ready after being forked
- enable more tests

chore(tests): update restart spec specs and plugin specs

---

.travis.yml
lib/launcher.ts
scripts/test.js
scripts/test_on_travis.sh
spec/ciFullConf.js
spec/errorTest/afterLaunchChangesExitCodeConf.js
spec/errorTest/baseCase/error_spec.js
spec/errorTest/baseCase/mocha_failure_spec.js
spec/errorTest/baseCase/single_failure_spec1.js
spec/errorTest/baseCase/single_failure_spec2.js
spec/errorTest/baseCase/slow_http_and_timeout_spec.js
spec/errorTest/baseCase/success_spec.js
spec/errorTest/baseCase/timeout_spec.js
spec/errorTest/browserStackAuthentication.js
spec/errorTest/debugMultiCapabilities.js
spec/errorTest/getMultiCapabilitiesConf.js
spec/errorTest/mochaFailureConf.js
spec/errorTest/multiFailureConf.js
spec/errorTest/pluginsFailingConf.js
spec/errorTest/sauceLabsAuthentication.js
spec/errorTest/shardedFailureConf.js
spec/errorTest/singleFailureConf.js
spec/errorTest/slowHttpAndTimeoutConf.js
spec/errorTest/timeoutConf.js
spec/plugins/plugins/failing_plugin.js

- Fix a missing await on createNextTaskRunner where the recursive call
should be awaited and if there are no new tasks to still resolve the
promise. Things were passing previously probably because we were
running tasks out of sync.
- Add in errorTest portion of the test suite
- Turn on the angular2 and unit tests.

chore(test): error tests fixed

---

lib/driverProviders/browserStack.ts
lib/driverProviders/direct.ts
lib/element.ts
lib/locators.ts

- remove imports that are not used
- clean up wdpromises

chore(cleanup): clean up imports and wdpromises

---

spec/basic/locators_spec.js

Removing the addMatchers test since we no longer support async calls
resolve with jasminewd since we removed jasminewd. Also Jasmine does
not appear to support async calls in custom expectations or the
compare method.

chore(test): remove jasmine addMatcher test

---

lib/browser.ts
lib/element.ts
lib/expectedConditions.ts
lib/locators.ts

Updated API examples to use async/await

---

lib/browser.ts
lib/driverProviders/attachSession.ts
lib/driverProviders/direct.ts
lib/driverProviders/driverProvider.ts
lib/driverProviders/mock.ts
lib/runner.ts
package-lock.json
package.json
scripts/errorTest.js
scripts/test.js
spec/basic/elements_spec.js
spec/basic/expected_conditions_spec.js
spec/basic/restart_spec.js
spec/driverProviders/local/local_spec.js
spec/interaction/interaction_spec.js
spec/unit/driverProviders/direct_test.js
spec/unit/driverProviders/local_test.js

- remove `.ready` since forking should automatically return a browser
- getNewDriver should return a promised WebDriver that can be awaited
- fix interaction tests and local driver tests
- update unit tests for async await due to getNewDriver fix
closes #5031

chore(browser): remove timing issues with restart and fork

---

lib/config.ts

This change tries to make the different proxies available easier to differentiate.
The sauceAgent key's comment said that adding a webDriverProxy would override this and this is not true.
sauceAgent is overwritten by sauceProxy since both are passed onto the saucelabs module.
See:
https://github.com/angular/protractor/blob/master/lib/driverProviders/sauce.ts#L60-L61
webDriverProxy on the other hand is passed onto the WebDriver session.
See:
https://github.com/angular/protractor/blob/master/lib/driverProviders/driverProvider.ts#L54
This means that if you're under a corporate proxy and need to proxy both Sauce Labs API calls as well as calls to the Selenium endpoint (ondemand.saucelabs.com) both sauceProxy/sauceAgent and webDriverProxy need to be used.

chore(config): Update docs regarding proxies

---

lib/expectedConditions.ts
lib/taskRunner.ts
spec/basic/expected_conditions_spec.js

- Use `() => Promise<boolean>` over `Function` typings.
- Fix an ExpectedConditions test where it was set to a const.
- Fix a TypeScript typing interface issue with RunResults in taskRunner.

chore(expectedConditions): update generic Function typings

---

CHANGELOG.md

updated `CHANGELOG.md` file for `v6.0.0` release, due to this [5204](https://github.com/angular/protractor/issues/5204)
Commits refered from this link
https://github.com/angular/protractor/commits/master

updated commit reference for v6.0.0 changelog #5204

---

lib/launcher.ts
lib/runnerCli.ts

This PR fixes the following lints : 
**1. refactor([launcher](https://github.com/angular/protractor/blob/master/lib/launcher.ts)):  removes unnecessary assignment**
Removes unnecessary assignment of `shortName` @ [line 58](https://github.com/angular/protractor/blob/master/lib/launcher.ts#L58)
**2. refactor([runnerCli](https://github.com/angular/protractor/blob/master/lib/runnerCli.ts)): convert `switch` to `if-else`**
Converts the `switch` to an `if-else` as the `switch` statement is made of only 2 branches. 😄

refactor to fix lints.

---

lib/element.ts

As per the selenium4 changelog removed WebElement getSize and getLocation for getRect.

fix(element): removed WebElement getSize and getLocation for getRect

---

docs/browser-setup.md

ChromeDriver at version 2.31 changed `chromeOptions` to `goog:ChromeOptions` ( [see: https://chromedriver.storage.googleapis.com/2.31/notes.txt](https://chromedriver.storage.googleapis.com/2.31/notes.txt) ).
While I was trying to use old version (that worked good for v.5.4.2), then I obtained following problems: https://stackoverflow.com/questions/58057678/angular-protractor-update-to-6-0-0-causes-browser-crashes
Following changes unifies configuration with Firefox and allows to easy find reason of problems. It works also for 5.4.2, see part of my test spec log, where `goog:chromeOptions` is visible:
```Capabilities {
map_:
Map {
'acceptInsecureCerts' => false,
'acceptSslCerts' => false,
'applicationCacheEnabled' => false,
'browserConnectionEnabled' => false,
'browserName' => 'chrome', …
```

docs(browser-setup): update Chrome configuration to v.6

---

DEVELOPER.md

`lib/debuger` folder and its content no longer exist. Removing that from developer doc.

fix(doc): removed reference to non-existing/deprecated section

---

docs/control-flow.md

The link was pointing to the wrong line.

fix(doc): update link to selenium promise manager option

---

.travis.yml
scripts/sauce_connect_setup.sh
scripts/travis_setup.sh

`travis_wait` is not needed if the sauce connect proxy logs are written to
stdout. This makes debugging proxy problems from the CI logs much
easier. This commit also updates the debugging command to use the
`--doctor` flag.
Other changes include:
1. Upgrade sauce-connect proxy from 4.4.1 to 4.5.4

ci: Log sauce connect proxy to stdout, remove travis_wait, upgrade proxy to 4.5.4

---

docs/faq.md
lib/cli.ts
package-lock.json
package.json
spec/driverProviderTest.js
testapp/scripts/web-server.js

Optimist has been deprecated over 2 years ago as has a security vulnerability. With this change we use it's successor `yargs`.
Closes: #5413
**_Kindly merge this to master and patch (release-5.4 branch)_**
//cc @IgorMinar

fix: security prototype pollution

---

package.json
release.md

Sets the package.json publishConfig to use the wombat-dressing-room
registry.

build: publish using wombat

---

README.md

Protractor 5 is compatible with nodejs v6 and v8 only.
Protractor 6 has been deprecated.
Protractor 7 is compatible with nodejs v10, v12, and newer.

doc: update compatibility change with nodejs
